apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig


metadata:
  name: weclouddata
  region: us-east-1

iam:
  withOIDC: true
  serviceAccounts:
    - metadata:
        name: ebs-csi-controller-sa
        namespace: kube-system
      wellKnownPolicies:
        ebsCSIController: true
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy
      roleName: AmazonEKS_EBS_CSI_DriverRole

nodeGroups:
  - name: ng-1
    instanceType: t3.large
    desiredCapacity: 1
    volumeSize: 100
    minSize: 1
    maxSize: 4
  - name: ng-2
    instanceType: t3.large
    desiredCapacity: 1
    volumeSize: 100
    minSize: 1
    maxSize: 4

