apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig


metadata:
  name: weclouddata
  region: us-east-1



nodeGroups:
  - name: ng-1
    instanceType: t4g.medium
    desiredCapacity: 1
    volumeSize: 100
    minSize: 1
    maxSize: 4
  - name: ng-2
    instanceType: t4g.medium
    desiredCapacity: 1
    volumeSize: 100
    minSize: 1
    maxSize: 4

